# Generated by Django 5.2.7 on 2025-11-06 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reapp', '0002_userprofile_profile_photo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
