# Generated by Django 5.1.2 on 2025-08-28 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0004_alter_news_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('author', models.CharField(blank=True, max_length=100)),
                ('date', models.DateField()),
                ('content', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, default='blog_images/default.jpg', null=True, upload_to='blog_images/')),
                ('likes', models.PositiveIntegerField(default=0)),
                ('category', models.CharField(blank=True, choices=[('web_development', 'Web Development'), ('ai_ml', 'AI & Machine Learning'), ('cybersecurity', 'Cybersecurity'), ('data_science', 'Data Science'), ('blockchain', 'Blockchain'), ('cloud_computing', 'Cloud Computing'), ('others', 'Others')], max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('comment', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='message.blog')),
            ],
        ),
    ]
