# Generated by Django 5.2.7 on 2025-11-06 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0006_blog_status_blog_submitted_at_blog_submitted_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('published', 'Published'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
