# Generated by Django 5.0.1 on 2024-02-02 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("team_gallary", "0003_alter_team_member_img"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="academic_background",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="team",
            name="contact_number",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="team",
            name="googlescholar_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="team",
            name="member_email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="team",
            name="member_location",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="team",
            name="professional_collaborations",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="team",
            name="professional_experience",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="team",
            name="professional_membership",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="team",
            name="researchgate_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="team",
            name="short_bio",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="team",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
