# Generated by Django 5.0.1 on 2024-02-02 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("team_gallary", "0004_team_academic_background_team_contact_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="contact_number",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="team",
            name="member_email",
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name="team",
            name="member_location",
            field=models.CharField(max_length=200),
        ),
    ]
