# Generated by Django 5.1.2 on 2025-01-03 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors_details', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
