# Generated by Django 5.0.1 on 2025-05-12 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Main session title, e.g., The International Joint Conference on Biometrics (IJCB 2025)', max_length=400)),
                ('location', models.CharField(help_text='e.g., Grant Front Osaka, Osaka, Japan', max_length=255)),
                ('date_range', models.CharField(help_text='e.g., September 8–11, 2025', max_length=100)),
                ('tagline', models.CharField(help_text='e.g., Call for Special Sessions', max_length=255)),
                ('session_name', models.CharField(help_text='e.g., Decentralised Identity and Biometric Authentication in Smart City Applications', max_length=400)),
                ('html_file', models.FileField(blank=True, null=True, upload_to='html/')),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
    ]
