# Generated by Django 5.1.2 on 2025-05-12 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='date_range',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='session',
            name='location',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='session',
            name='session_name',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='session',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='tagline',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='session',
            name='title',
            field=models.CharField(max_length=400),
        ),
    ]
