# Generated by Django 5.1.2 on 2024-12-31 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('private_ip', models.CharField(blank=True, max_length=50, null=True)),
                ('user_agent', models.TextField()),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('visit_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
