# Generated by Django 5.1.2 on 2025-08-14 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication_project', '0004_project_url_alter_project_durations_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=200)),
                ('logo', models.ImageField(upload_to='client_logos/')),
                ('client_description', models.TextField()),
                ('website', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
