# Generated by Django 5.1.2 on 2025-10-10 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication_project', '0005_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Data Science', 'Data Science'), ('Software Development', 'Software Development'), ('Cybersecurity', 'Cybersecurity'), ('Blockchain', 'Blockchain'), ('Consulting', 'Consulting'), ('Other Services', 'Other Services')], max_length=50)),
                ('service_name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('icon', models.CharField(blank=True, help_text="Enter the CSS class for the icon, e.g., 'bi bi-laptop'", max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
    ]
